import { useTranslation } from 'react-i18next';
import { ProjectProps } from '../../types/projectsTypes';

const ProjectsData = (): ProjectProps[] => {
    const { t } = useTranslation();

    return [
        {
            id: 1,
            imgLink: 'https://i.ibb.co/f9bqSG9/israel.jpg',
            description: {
                title: 'landing page israel',
                subTitle: t`israel.subTitle`,
                techTasks: {
                    common: t`israel.techTasks`,
                    items: [
                        t`israel.techTasksFirst`,
                        t`israel.techTasksSecond`,
                        t`israel.techTasksThird`,
                        t`israel.techTasksFourth`,
                        t`israel.techTasksFifth`,
                        t`israel.techTasksSixth`,
                        t`israel.techTasksSeventh`,
                        t`israel.techTasksEighth`,
                        t`israel.techTasksNinth`,
                        t`israel.techTasksTenth`,
                    ],
                },
                stack: [
                    'html/css',
                    'scss',
                    'js',
                    'gulp',
                    'webpack-stream',
                    'swiper',
                ],
            },
            gitLink: 'https://github.com/SLain123/israel_private',
            prodLink: 'https://israel-2mbcerdp1-slain123.vercel.app/',
        },
        {
            id: 2,
            imgLink: 'https://i.ibb.co/tP2N4J3/movie.jpg',
            description: {
                title: 'movie db',
                subTitle: t`movie.subTitle`,
                techTasks: {
                    common: t`movie.techTasks`,
                    items: [
                        t`movie.techTasksFirst`,
                        t`movie.techTasksSecond`,
                        t`movie.techTasksThird`,
                        t`movie.techTasksFourth`,
                        t`movie.techTasksFifth`,
                        t`movie.techTasksSixth`,
                    ],
                },
                stack: [
                    'html/css',
                    'js',
                    'react',
                    'webpack',
                    'antd',
                    'date-fns',
                    'lodash',
                    'prop-types',
                ],
            },
            gitLink:
                'https://github.com/SLain123/Mini_Project_React/tree/master/moviesApp',
            prodLink: 'https://movie-app-topaz.vercel.app/',
        },
        {
            id: 3,
            imgLink: 'https://i.ibb.co/2YdgYpD/avia.jpg',
            description: {
                title: 'avia sales app',
                subTitle: t`avia.subTitle`,
                techTasks: {
                    common: t`avia.techTasks`,
                    items: [
                        t`avia.techTasksFirst`,
                        t`avia.techTasksSecond`,
                        t`avia.techTasksThird`,
                        t`avia.techTasksFourth`,
                        t`avia.techTasksFifth`,
                        t`avia.techTasksSixth`,
                        t`avia.techTasksSeventh`,
                    ],
                },
                stack: [
                    'html/css',
                    'scss',
                    'js',
                    'react',
                    'redux',
                    'webpack',
                    'antd',
                    'date-fns',
                    'lodash',
                    'prop-types',
                ],
            },
            gitLink: 'https://github.com/SLain123/Avia',
            prodLink: 'https://avia-rho.vercel.app/',
        },
        {
            id: 4,
            imgLink: 'https://i.ibb.co/r6J0HWx/traffic-light.jpg',
            description: {
                title: 'traffic light',
                subTitle: t`traffic.subTitle`,
                techTasks: {
                    common: t`traffic.techTasks`,
                    items: [
                        t`traffic.techTasksFirst`,
                        t`traffic.techTasksSecond`,
                        t`traffic.techTasksThird`,
                        t`traffic.techTasksFourth`,
                        t`traffic.techTasksFifth`,
                        t`traffic.techTasksSixth`,
                        t`traffic.techTasksSeventh`,
                        t`traffic.techTasksEighth`,
                        t`traffic.techTasksNinth`,
                        t`traffic.techTasksTenth`,
                        t`traffic.techTasksEleventh`,
                    ],
                },
                stack: [
                    'html/css',
                    'scss',
                    'ts',
                    'react',
                    'redux',
                    'react-router',
                    'webpack',
                ],
            },
            gitLink: 'https://github.com/SLain123/TrafficLight',
            prodLink: 'https://traffic-light-umber.vercel.app/',
        },
        {
            id: 5,
            imgLink: 'https://i.ibb.co/Fhxck7X/witcher.jpg',
            description: {
                title: 'the witcher',
                subTitle: t`witcher.subTitle`,
                techTasks: {
                    common: t`witcher.techTasks`,
                    items: [
                        t`witcher.techTasksFirst`,
                        t`witcher.techTasksSecond`,
                        t`witcher.techTasksThird`,
                        t`witcher.techTasksFourth`,
                    ],
                },
                stack: ['html/css', 'js', 'gulp'],
            },
            gitLink: 'https://github.com/SLain123/The_witcher_Private',
            prodLink: 'https://witcher-delta.vercel.app/',
        },
        {
            id: 6,
            imgLink: 'https://i.ibb.co/qRcZ5Rf/book.jpg',
            description: {
                title: 'book store',
                subTitle: t`book.subTitle`,
                techTasks: {
                    common: t`book.techTasks`,
                    items: [
                        t`book.techTasksFirst`,
                        t`book.techTasksSecond`,
                        t`book.techTasksThird`,
                        t`book.techTasksFourth`,
                    ],
                },
                stack: [
                    'html/css',
                    'scss',
                    'js',
                    'react',
                    'redux',
                    'react-router',
                    'webpack',
                ],
            },
            gitLink: 'https://github.com/SLain123/book_store',
            prodLink: 'https://book-store-steel.vercel.app/',
        },
        {
            id: 7,
            imgLink: 'https://i.ibb.co/jhytvsZ/constructor.jpg',
            description: {
                title: 'web constructor',
                subTitle: t`constructor.subTitle`,
                techTasks: {
                    common: t`constructor.techTasks`,
                    items: [
                        t`constructor.techTasksFirst`,
                        t`constructor.techTasksSecond`,
                        t`constructor.techTasksThird`,
                        t`constructor.techTasksFourth`,
                        t`constructor.techTasksFifth`,
                        t`constructor.techTasksSixth`,
                        t`constructor.techTasksSeventh`,
                        t`constructor.techTasksEighth`,
                        t`constructor.techTasksNinth`,
                    ],
                },
                stack: ['html/css', 'js', 'parcel', 'font-awesome', 'jszip'],
            },
            gitLink: 'https://github.com/SLain123/Constructor',
            prodLink: 'https://constructor.vercel.app/',
        },
        {
            id: 8,
            imgLink: 'https://i.ibb.co/80y45Tc/realworld-blog.jpg',
            description: {
                title: 'realworld blog',
                subTitle: t`blog.subTitle`,
                techTasks: {
                    common: t`blog.techTasks`,
                    items: [
                        t`blog.techTasksFirst`,
                        t`blog.techTasksSecond`,
                        t`blog.techTasksThird`,
                        t`blog.techTasksFourth`,
                        t`blog.techTasksFifth`,
                        t`blog.techTasksSixth`,
                        t`blog.techTasksSeventh`,
                        t`blog.techTasksEighth`,
                        t`blog.techTasksNinth`,
                        t`blog.techTasksTenth`,
                    ],
                },
                stack: [
                    'html/css',
                    'scss',
                    'js',
                    'react',
                    'redux',
                    'react-router',
                    'react-spring',
                    'react-hook-form',
                    'react-markdown',
                    'antd',
                    'date-fns',
                    'lodash',
                    'prop-types',
                    'webpack',
                ],
            },
            gitLink: 'https://github.com/SLain123/blog',
            prodLink: 'https://blog-self-theta.vercel.app/',
        },
        {
            id: 9,
            imgLink: 'https://i.ibb.co/7gRVXsV/cps.jpg',
            description: {
                title: 'cps',
                subTitle: t`cps.subTitle`,
                techTasks: {
                    common: t`cps.techTasks`,
                    items: [
                        t`cps.techTasksFirst`,
                        t`cps.techTasksSecond`,
                        t`cps.techTasksThird`,
                        t`cps.techTasksFourth`,
                        t`cps.techTasksFifth`,
                    ],
                },
                stack: [
                    'html/css',
                    'scss',
                    'js',
                    'gulp',
                    'swiper',
                    'webpack-stream',
                ],
            },
            gitLink: 'https://github.com/SLain123/cps_store',
            prodLink: 'https://cps-store.vercel.app/',
        },
    ];
};

export default ProjectsData;
